#!/bin/bash

# Fix intel color corruption
export INTEL_DEBUG=norbc
# Enabling full multi threading support for games with Mesa
export mesa_glthread=true

# Plop GAMESCOPE_MODE_SAVE_FILE into $XDG_CONFIG_HOME (defaults to ~/.config).
export GAMESCOPE_MODE_SAVE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/modes.cfg"

# Make path to gamescope mode save file.
mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
touch "$GAMESCOPE_MODE_SAVE_FILE"

# Mangohud config
export MANGOHUD_CONFIGFILE="${HOME}/.mangohud/MangoHud.conf"
mkdir -p "$(dirname "$MANGOHUD_CONFIGFILE")"
echo "no_display" > "$MANGOHUD_CONFIGFILE"

# Steam and Desktop session configuration
export HOMETEST_DESKTOP=1
export HOMETEST_USER=gamer
export HOMETEST_DESKTOP_USER=gamer
export HOMETEST_DESKTOP_SESSION=gnome

# Gamescope specific configuration
export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
export GAMESCOPE_DISABLE_ASYNC_FLIPS=1
export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)
export STEAM_GAMESCOPE_VRR_SUPPORTED=1
export STEAM_GAMESCOPE_DYNAMIC_REFRESH_IN_STEAM_SUPPORTED=0

# MangoApp configuration
export STEAM_USE_MANGOAPP=1
export STEAM_DISABLE_MANGOAPP_ATOM_WORKAROUND=1
export STEAM_MANGOAPP_PRESETS_SUPPORTED=1
export STEAM_MANGOAPP_HORIZONTAL_SUPPORTED=1

# Performance configuration
export STEAM_GAMESCOPE_FANCY_SCALING_SUPPORT=1
export STEAM_GAMESCOPE_DYNAMIC_FPSLIMITER=1
export STEAM_GAMESCOPE_HAS_TEARING_SUPPORT=1
export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
export STEAM_GAMESCOPE_COLOR_TOYS=1
export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
export STEAM_GAMESCOPE_NIS_SUPPORTED=1
export STEAM_GAMESCOPE_VRR_SUPPORTED=1
export STEAM_GAMESCOPE_DYNAMIC_REFRESH_IN_STEAM_SUPPORTED=0

# General configuration
export STEAM_DISPLAY_REFRESH_LIMITS=30,40,60
export STEAM_MULTIPLE_XWAYLANDS=1
export XCURSOR_SIZE=1024
export XCURSOR_THEME=steam
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
export WINEDLLOVERRIDES=dxgi=n
export QT_IM_MODULE=steam
export GTK_IM_MODULE=Steam

# RayTracing/Vulkan configuration
export VKVD3D_CONFIG=dxr11,dxr
export VKVD3D_FEATURE_LEVEL=12_2
export vk_xwayland_wait_ready=false

# HDR configuration
export DXVK_HDR=1
export STEAM_GAMESCOPE_HDR_SUPPORTED=1
export ENABLE_GAMESCOPE_WSI=1

# Steam OS Sentinels ----------------------------------------------------
# Workaround for steam getting killed immediatly during reboot
export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"

# Workaround for steam getting killed immediatly during shutdown
# Same idea as reboot sentinel above
export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"

# Cursor configuration
CURSOR_FILE="${HOME}/.local/share/Steam/tenfoot/resource/images/cursors/arrow_right.png"
CURSOR="--cursor ${CURSOR_FILE}"

# Preparing gamescope session run arguments
RESOLUTION=""
VRR_ARGS=""
SDR_GAMUT="--sdr-gamut-wideness 1"

if [ -n "$SCREEN_WIDTH" ] && [ -n "$SCREEN_HEIGHT" ] ; then
	RESOLUTION="-W $SCREEN_WIDTH -H $SCREEN_HEIGHT"
fi

if [ -n "$SCREEN_REFRESH_RATE" ]; then
	VRR_ARGS="-r $SCREEN_REFRESH_RATE"
fi

# Setup socket for gamescope

# -- Create run directory file for startup and stats sockets
tmpdir="$([[ -n ${XDG_RUNTIME_DIR+x} ]] && mktemp -p "$XDG_RUNTIME_DIR" -d -t gamescope.XXXXXXX)"
socket="${tmpdir:+$tmpdir/startup.socket}"
stats="${tmpdir:+$tmpdir/stats.pipe}"

# -- Fail early if we don't have a proper runtime directory setup
if [[ -z $tmpdir || -z ${XDG_RUNTIME_DIR+x} ]]; then
	echo >&2 "!! Failed to find run directory in which to create stats session sockets (is \$XDG_RUNTIME_DIR set?)"
	exit 0
fi

export GAMESCOPE_STATS="$stats"
mkfifo -- "$stats"
mkfifo -- "$socket"

# Attempt to claim global session if we're the first one running (e.g. /run/1000/gamescope)
linkname="gamescope-stats"
#   shellcheck disable=SC2031 # (broken warning)
sessionlink="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/}${linkname}" # Account for XDG_RUNTIME_DIR="" (notfragileatall)
lockfile="$sessionlink".lck
exec 9>"$lockfile" # Keep as an fd such that the lock lasts as long as the session if it is taken
if flock -n 9 && rm -f "$sessionlink" && ln -sf "$tmpdir" "$sessionlink"; then
	# Took the lock.  Don't blow up if those commands fail, though.
	echo >&2 "Claimed global gamescope stats session at \"$sessionlink\""
else
	echo >&2 "!! Failed to claim global gamescope stats session"
fi

ulimit -n 524288

# Source user configuration from ~/.config/environment.d
set -a
for i in "${HOME}"/.config/environment.d/*.conf ;
do
    [[ -f "${i}" ]] && . "${i}"
done
set +a

GAMESCOPECMD="/usr/bin/gamescope \
	$CURSOR \
	$RESOLUTION \
	$VRR_ARGS \
	$SDR_GAMUT \
	-e \
	--max-scale 2 \
	--xwayland-count 2 \
	--generate-drm-mode cvt \
	--immediate-flips \
	--adaptive-sync \
	--hdr-enabled \
	--hdr-itm-enable \
	-O *,eDP-1 \
	-F fsr \
	-f \
	--expose-wayland \
	--default-touch-mode 4 \
	--hide-cursor-delay 3000 \
	--fade-out-duration 200 \
	-R $socket -T $stats"

# Start gamescope compositor, log it's output and background it
$GAMESCOPECMD > "${HOME}"/.gamescope-stdout.log 2>&1 &
gamescope_pid="$!"

if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
	export DISPLAY="$response_x_display"
	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
	# We're done!
else
	kill -9 "$gamescope_pid"
	wait
	exit 0
	# Systemd or Session manager will have to restart session
fi

# If we have mangoapp binary start it
if command -v mangoapp > /dev/null; then
	mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1 &
fi

# Start Steam client
STEAMCMD="steam -gamepadui -steamos -steamdeck -steampal"
$STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1

# When the client exits, kill gamescope nicely
kill $gamescope_pid

# Start a background sleep for five seconds because we don't trust it
sleep 5 &
sleep_pid="$!"

# Catch reboot and poweroof sentinels here
if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
	reboot
fi
if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
	poweroff
fi

# Wait for gamescope or the sleep to finish for timeout purposes
ret=0
wait -n $gamescope_pid $sleep_pid || ret=$?

# If we get a SIGTERM/etc while waiting this happens.  Proceed to kill -9 everything but complain
if [[ $ret = 127 ]]; then
	echo >&2 "gamescope-session: Interrupted while waiting on teardown, force-killing remaining tasks"
fi

# Kill all remaining jobs and warn if unexpected things are in there (should be just sleep_pid, unless gamescope failed
# to exit in time or we hit the interrupt case above)
for job in $(jobs -p); do
	# Warn about unexpected things
	if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
		echo >&2 "gamescope-session: gamescope timed out while exiting, killing"
	elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
		echo >&2 "gamescope-session: unexpected background pid $job at teardown: "
		# spew some debug about it
		ps -p "$job" >&2
	fi
	kill -9 "$job"
done