#!/bin/bash

# Plop GAMESCOPE_MODE_SAVE_FILE into $XDG_CONFIG_HOME (defaults to ~/.config).
export GAMESCOPE_MODE_SAVE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/modes.cfg"

# Make path to gamescope mode save file.
mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
touch "$GAMESCOPE_MODE_SAVE_FILE"

# Mangohud config
export MANGOHUD_CONFIGFILE=/usr/share/doc/mangohud/MangoHud.conf
mkdir -p "$(dirname "$MANGOHUD_CONFIGFILE")"
echo "no_display" > "$MANGOHUD_CONFIGFILE"

# Steam and Desktop session configuration
export HOMETEST_DESKTOP=1
export HOMETEST_USER=gamer
export HOMETEST_DESKTOP_USER=gamer
export HOMETEST_DESKTOP_SESSION=gnome-wayland

# Gamescope specific configuration
export GAMESCOPE_DISABLE_ASYNC_FLIPS=1
export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)

# MangoApp configuration
export STEAM_USE_MANGOAPP=1
export STEAM_DISABLE_MANGOAPP_ATOM_WORKAROUND=1
export STEAM_MANGOAPP_PRESETS_SUPPORTED=1
export STEAM_MANGOAPP_HORIZONTAL_SUPPORTED=1

# Performance configuration
export STEAM_GAMESCOPE_FANCY_SCALING_SUPPORT=1
export STEAM_GAMESCOPE_DYNAMIC_FPSLIMITER=1
export STEAM_GAMESCOPE_HAS_TEARING_SUPPORT=1
export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
export STEAM_GAMESCOPE_COLOR_TOYS=1
export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
export STEAM_GAMESCOPE_NIS_SUPPORTED=1

# General configuration
export STEAM_DISPLAY_REFRESH_LIMITS=30,40,60
export STEAM_MULTIPLE_XWAYLANDS=1
export XCURSOR_SIZE=1024
export XCURSOR_THEME=steam
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
export WINEDLLOVERRIDES=dxgi=n
export QT_IM_MODULE=steam
export GTK_IM_MODULE=Steam

# RayTracing/Vulkan configuration
export VKVD3D_CONFIG=dxr11,dxr
export VKVD3D_FEATURE_LEVEL=12_2
export vk_xwayland_wait_ready=false

# Cursor configuration
CURSOR_FILE="${HOME}/.local/share/Steam/tenfoot/resource/images/cursors/arrow_right.png"
CURSOR="--cursor ${CURSOR_FILE}"

# Preparing gamescope session run arguments
RESOLUTION="-W 3840 -H 2160 -w 3840 -h 2160"
VRR_ARGS=""
SDR_GAMUT="--sdr-gamut-wideness 1"

# Setup socket for gamescope

# -- Create run directory file for startup and stats sockets
tmpdir="$([[ -n ${XDG_RUNTIME_DIR+x} ]] && mktemp -p "$XDG_RUNTIME_DIR" -d -t gamescope.XXXXXXX)"
socket="${tmpdir:+$tmpdir/startup.socket}"
stats="${tmpdir:+$tmpdir/stats.pipe}"

# -- Fail early if we don't have a proper runtime directory setup
if [[ -z $tmpdir || -z ${XDG_RUNTIME_DIR+x} ]]; then
	echo >&2 "!! Failed to find run directory in which to create stats session sockets (is \$XDG_RUNTIME_DIR set?)"
	exit 0
fi

export GAMESCOPE_STATS="$stats"
mkfifo -- "$stats"
mkfifo -- "$socket"

# Attempt to claim global session if we're the first one running (e.g. /run/1000/gamescope)
linkname="gamescope-stats"
#   shellcheck disable=SC2031 # (broken warning)
sessionlink="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/}${linkname}" # Account for XDG_RUNTIME_DIR="" (notfragileatall)
lockfile="$sessionlink".lck
exec 9>"$lockfile" # Keep as an fd such that the lock lasts as long as the session if it is taken
if flock -n 9 && rm -f "$sessionlink" && ln -sf "$tmpdir" "$sessionlink"; then
	# Took the lock.  Don't blow up if those commands fail, though.
	echo >&2 "Claimed global gamescope stats session at \"$sessionlink\""
else
	echo >&2 "!! Failed to claim global gamescope stats session"
fi

GAMESCOPECMD="/usr/bin/gamescope \
	$CURSOR \
	$RESOLUTION \
	$VRR_ARGS \
	$SDR_GAMUT \
	-U \
	-e \
	--max-scale 2 \
	--xwayland-count 2 \
	--generate-drm-mode cvt \
	--immediate-flips \
	--adaptive-sync \
	-O *,eDP-1 \
	-f \
	--default-touch-mode 4 \
	--hide-cursor-delay 3000 \
	--fade-out-duration 200 \
	-R $socket -T $stats"

# Start gamescope compositor, log it's output and background it
$GAMESCOPECMD > "${HOME}"/.gamescope-stdout.log 2>&1 &
gamescope_pid="$!"

if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
	export DISPLAY="$response_x_display"
	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
	# We're done!
else
	kill -9 "$gamescope_pid"
	wait
	exit 0
	# Systemd or Session manager will have to restart session
fi

# If we have mangoapp binary start it
if command -v mangoapp > /dev/null; then
    mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1 &
fi

# Start Steam client
STEAMCMD="steam -gamepadui -steamos -steamdeck -steampal"
$STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1

# When the client exits, kill gamescope nicely
kill $gamescope_pid