#!/bin/bash

# Plop GAMESCOPE_MODE_SAVE_FILE into $XDG_CONFIG_HOME (defaults to ~/.config).
export GAMESCOPE_MODE_SAVE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/modes.cfg"

# Make path to gamescope mode save file.
mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
touch "$GAMESCOPE_MODE_SAVE_FILE"

# Steam and Desktop session configuration
export HOMETEST_DESKTOP=1
export HOMETEST_USER=gamer
export HOMETEST_DESKTOP_USER=gamer
export HOMETEST_DESKTOP_SESSION=gnome-wayland

# Gamescope specific configuration
export GAMESCOPE_DISABLE_ASYNC_FLIPS=1
export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)

# MangoApp configuration
export STEAM_USE_MANGOAPP=1
export STEAM_DISABLE_MANGOAPP_ATOM_WORKAROUND=1
export STEAM_MANGOAPP_PRESETS_SUPPORTED=1
export STEAM_MANGOAPP_HORIZONTAL_SUPPORTED=1

# Performance configuration
export STEAM_GAMESCOPE_FANCY_SCALING_SUPPORT=1
export STEAM_GAMESCOPE_DYNAMIC_FPSLIMITER=1
export STEAM_GAMESCOPE_HAS_TEARING_SUPPORT=1
export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
export STEAM_GAMESCOPE_COLOR_TOYS=1
export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
export STEAM_GAMESCOPE_NIS_SUPPORTED=1

# General configuration
export STEAM_DISPLAY_REFRESH_LIMITS=30,40,60
export STEAM_MULTIPLE_XWAYLANDS=1
export XCURSOR_SIZE=1024
export XCURSOR_THEME=steam
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
export WINEDLLOVERRIDES=dxgi=n
export QT_IM_MODULE=steam
export GTK_IM_MODULE=Steam

# RayTracing/Vulkan configuration
export VKVD3D_CONFIG=dxr11,dxr
export VKVD3D_FEATURE_LEVEL=12_2
export vk_xwayland_wait_ready=false

# Cursor configuration
CURSOR_FILE="${HOME}/.local/share/Steam/tenfoot/resource/images/cursors/arrow_right.png"
CURSOR="--cursor ${CURSOR_FILE}"

# Preparing gamescope session run arguments
RESOLUTION="-W 3840 -H 2160 -w 3840 -h 2160"
VRR_ARGS=""
SDR_GAMUT="--sdr-gamut-wideness 1"

GAMESCOPECMD="/usr/bin/gamescope \
	$CURSOR \
	$RESOLUTION \
	$VRR_ARGS \
	$SDR_GAMUT \
	-e \
	--max-scale 2 \
	--xwayland-count 2 \
	--generate-drm-mode cvt \
	--immediate-flips \
	--adaptive-sync \
	-O *,eDP-1 \
	-f \
	--default-touch-mode 4 \
	--hide-cursor-delay 3000 \
	--fade-out-duration 200 \
    -R $socket -T $stats"

# Start gamescope compositor, log it's output and background it
$GAMESCOPECMD > "${HOME}"/.gamescope-stdout.log 2>&1 &
gamescope_pid="$!"

if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
	export DISPLAY="$response_x_display"
	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
	# We're done!
else
	kill -9 "$gamescope_pid"
	wait
	exit 0
	# Systemd or Session manager will have to restart session
fi

# If we have mangoapp binary start it
if command -v mangoapp > /dev/null; then
    mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1 &
fi

# Start Steam client
STEAMCMD="steam -gamepadui -steamos -steamdeck -steampal"
$STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1

# When the client exits, kill gamescope nicely
kill $gamescope_pid