#!/bin/bash

#set -e

create_backup() {
    FILE="$1"
    BACKUP="${2:-true}"  # Default value is true if not provided

    if [ "$BACKUP" = true ] && [ -f "$FILE" ]; then
        BACKUP_FILE="${FILE}.old"
        sudo rm -rf "$BACKUP_FILE"
        #sudo cp "$FILE" "$BACKUP_FILE"
    fi
}

copy_local() {
  SRC_FILE="$1"
  DEST_FILE="$2"
  EXECUTABLE="${2:-false}"

  if [ -f "$DEST_FILE" ]; then
    create_backup "$DEST_FILE"
  fi

  sudo mkdir -p "$(dirname "$DEST_FILE")"
  cat "$SRC_FILE" | sudo tee "$DEST_FILE"

  if [ "$EXECUTABLE" = "true" ]; then
    sudo chmod +x "$DEST_FILE"
  fi
}

configure_xdm() {
  XDM_CONF_FILE="/var/lib/AccountsService/users/gamer"

  {
    echo "[User]"
    echo "Session=gamescope-custom"
    echo "Icon=/home/gamer/.face"
    echo "SystemAccount=false"
  } | sudo tee "$XDM_CONF_FILE"
}

# Copying local files
copy_local "rootfs/usr/bin/gnome-session-select" "/usr/bin/gnome-session-select" "true"
copy_local "rootfs/usr/bin/steamos-session-select" "/usr/bin/steamos-session-select" "true"
copy_local "rootfs/usr/bin/return-to-gamemode" "/usr/bin/return-to-gamemode" "true"

copy_local "rootfs/usr/share/wayland-sessions/gnome-wayland-oneshot.desktop" "/usr/share/wayland-sessions/gnome-wayland-oneshot.desktop"
copy_local "rootfs/usr/share/wayland-sessions/gnome-oneshot.desktop" "/usr/share/wayland-sessions/gnome-oneshot.desktop"
copy_local "rootfs/usr/share/wayland-sessions/gamescope-custom.desktop" "/usr/share/wayland-sessions/gamescope-custom.desktop"
copy_local "rootfs/usr/share/wayland-sessions/gamescope-session.desktop" "/usr/share/wayland-sessions/gamescope-session.desktop"
copy_local "rootfs/usr/share/applications/return-to-gamemode.desktop" "/usr/share/applications/return-to-gamemode.desktop"

copy_local "rootfs/usr/share/gamescope-custom/gamescope-script" "/usr/share/gamescope-custom/gamescope-script" "true"

# Rebuilding application database
copy_local "/usr/share/applications/return-to-gamemode.desktop" "$HOME/.local/share/applications/Return to Gamemode.desktop"
sudo update-desktop-database

# Configuring Lightdm as the login manager, if set
if [[ "$1" == "--lightdm" ]]; then
  configure_lightdm
else
  configure_xdm
fi

sudo reboot -f
