#!/usr/bin/bash

source /etc/default/desktop-wayland

# IMAGE_INFO="/usr/share/ublue-os/image-info.json"
# BASE_IMAGE_NAME=$(jq -r '."base-image-name"' < $IMAGE_INFO)
BASE_IMAGE_NAME="silverblue"

USER=$(id -nu 1000)
HOME=$(getent passwd $USER | cut -d: -f6)

# SteamOS lightdm config
CONF_FILE='/usr/share/lightdm/lightdm.conf.d/steamos.conf'
AUTOLOGIN_CONF='/usr/share/lightdm/lightdm.conf.d/zz-steamos-autologin.conf'
DESKTOP_AUTOLOGIN='/etc/bazzite/desktop_autologin'

# Avoid autologin conflict
if [[ -f ${AUTOLOGIN_CONF} ]]; then
  rm -f ${AUTOLOGIN_CONF}
fi

# Configure autologin if Steam has been updated
if [ -f $HOME/.local/share/Steam/ubuntu12_32/steamui.so ]; then
  sed -i 's/.*autologin-session=.*/autologin-session=gamescope-session/g' ${CONF_FILE}
elif [[ ${BASE_IMAGE_NAME} =~ "kinoite" ]]; then
  if ${DESKTOP_WAYLAND}; then
    sed -i 's/.*autologin-session=.*/autologin-session=plasma/g' ${CONF_FILE}
  else
    sed -i 's/.*autologin-session=.*/autologin-session=plasmax11/g' ${CONF_FILE}
  fi
elif [[ ${BASE_IMAGE_NAME} =~ "silverblue" ]]; then
  if ${DESKTOP_WAYLAND}; then
    sed -i 's/.*autologin-session=.*/autologin-session=gnome-wayland/g' ${CONF_FILE}
  else
    sed -i 's/.*autologin-session=.*/autologin-session=gnome-xorg/g' ${CONF_FILE}
  fi
fi
sed -i 's/.*autologin-user=.*/autologin-user='${USER}'/g' ${CONF_FILE}
