#!/usr/bin/bash

USER=$(id -nu 1000)
HOME=$(getent passwd $USER | cut -d: -f6)

# SteamOS LIUGHTDM config
LIGHTDM_CONF='/etc/lightdm/lightdm.conf.d/steamos.conf'
AUTOLOGIN_CONF='/etc/lightdm/lightdm.conf.d/zz-steamos-autologin.conf'

{
  echo "[Seat:*]"
  echo "autologin-session=gamescope-session"
} > "$AUTOLOGIN_CONF"

sed -i 's/.*autologin-user=.*/autologin-user='${USER}'/g' ${LIGHTDM_CONF}
