name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare Distribution Folder
        id: prepare_dist_folder
        run: mkdir dist

      - name: Create Zip
        id: create_zip
        run: zip -r -q "dist/release_${{ github.ref_name }}.zip" .

      - name: Github commit and push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Zipping and releasing $ {{ github.ref_name }}"
          files: "dist/release_${{ github.ref_name }}.zip"
          branch: main
