name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare Distribution Folder
        id: prepare_dist_folder
        run: mkdir dist

      - name: Create Zip
        id: create_zip
        run: zip -r -q "dist/release_$GITHUB_REF_NAME.zip" .

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: "['dist/release_$GITHUB_REF_NAME.zip']"
          message: "Versioning zip for release $GITHUB_REF_NAME"
          push: true
