name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare Distribution Folder
        id: prepare_dist_folder
        run: mkdir dist

      - name: Create Zip
        id: create_zip
        run: zip -r -q "dist/release_${{ github.ref_name }}.zip" .

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Commit and Push Zip
        run: |
          git config --global user.name "Github Gamescope Session Bot"
          git config --global user.email "@githubgamescopebot"
          git add -A
          git commit -m "Zipping and releasing $ {{ github.ref_name }}"
