name: Build and Release

on:
  workflow_run:
    workflows:
      - 'Build and Release'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Version
        id: extract_version
        run: echo "VERSION=$(echo ${{ steps.create_release.outputs.release }} | cut -d'/' -f7)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**  # Assuming your build output is in the dist directory
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: "release_${{ env.VERSION }}.zip"
          path: dist/
          directory: .
          exclusions: |
            dist/**
          type: zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Extract Version
        id: extract_version
        run: echo "VERSION=$(echo ${{ steps.create_release.outputs.release }} | cut -d'/' -f7)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "release_${{ env.VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Version as Release Note
        run: echo "## Release ${{ env.VERSION }}" > release_notes.md

      - name: Attach Release Note
        run: gh release upload ${{ env.VERSION }} release_notes.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
